# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: "jus d’orange frais")
Ingredient.create(name: "jus d’ananas")
Ingredient.create(name: "jus de citron frais")
Ingredient.create(name: "jus de citron vert frais")
Ingredient.create(name: "jus de pomme")
Ingredient.create(name: "morceaux de fruits frais aux choix")
Ingredient.create(name: "miel")
Ingredient.create(name: "sirop de grenadine")
Ingredient.create(name: "eau gazeuse")
Ingredient.create(name: "jus de tomate")
Ingredient.create(name: "sucre roux")
Ingredient.create(name: "lait")
Ingredient.create(name: "jus de canneberge")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Rhum blanc")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Indian Tonic")
Ingredient.create(name: "Ginger ale")
Ingredient.create(name: "limonade")
Ingredient.create(name: "cola")
Ingredient.create(name: "crème de coco")
Ingredient.create(name: "lait de coco")
Ingredient.create(name: "Malibu")
Ingredient.create(name: "Passoa")
Ingredient.create(name: "sirop de fraise")
Ingredient.create(name: "sirop d'orgeat")
Ingredient.create(name: "jus d’abricot")
